services:

  api:

    build: .

    ports:

      - "3001:3001"
      
    env_file:

      - .env

    volumes:
      - .:/app
      - /app/node_modules
    depends_on:

      - mongo

  mongo:
  
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: