
@baseUrl=http://localhost:3001/api
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "abderrahimghmouch@gmail.com",
  "password": "123456789"
}

###

GET {{baseUrl}}/api/unko

###

POST {{baseUrl}}/auth/login

Content-Content-Type: application/json:

{email:abderrahimghmouch@gmail.com
pas
}



